name: Run OSAT Simulation
#
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install simpy numpy pandas matplotlib seaborn statsmodels "ray[rllib]" gymnasium

    - name: Run simulation
      run: python run_simulation.py
